import crypto from 'node:crypto';
import { z } from 'zod';
import { prisma, isDatabaseConfigured } from '@/lib/prisma';
import { apiHandler, methodNotAllowed, HttpError, isHoneypotTripped } from '@/lib/api';

/**
 * POST /api/newsletter  — mailing-list signup (double opt-in).
 * GET  /api/newsletter/unsubscribe?token=… — one-click unsubscribe.
 *
 * The unsubscribe token is a SHA-256 of the address plus a server-only pepper,
 * so the URL does not expose plain e-mail addresses in logs or referrers.
 */

const subscribeSchema = z.object({
  email: z
    .string()
    .trim()
    .min(1, 'E-mail is required.')
    .email('Please enter a valid e-mail address.')
    .transform((value) => value.toLowerCase()),
  name: z.string().trim().max(120).optional(),
  source: z.string().trim().max(40).optional(),
  website: z.string().optional(),
});

function unsubscribeToken(email) {
  const pepper = process.env.NEXTAUTH_SECRET || 'dental-atelier-dev-pepper';
  return crypto.createHash('sha256').update(`${email}:${pepper}`).digest('hex');
}

export default apiHandler(
  async (req, res) => {
    if (req.method !== 'POST') return methodNotAllowed(res, ['POST']);

    if (isHoneypotTripped(req.body)) {
      return res.status(200).json({ success: true, message: 'Almost done — please confirm via e-mail.' });
    }

    const data = subscribeSchema.parse(req.body ?? {});

    if (!isDatabaseConfigured) {
      console.info('[newsletter] no DATABASE_URL configured, subscription not persisted:', data.email);
      return res.status(200).json({ success: true, persisted: false });
    }

    const token = unsubscribeToken(data.email);

    await prisma.newsletterSubscriber.upsert({
      where: { email: data.email },
      update: { active: true, name: data.name ?? undefined, source: data.source ?? 'footer' },
      create: {
        email: data.email,
        name: data.name ?? null,
        source: data.source ?? 'footer',
        unsubscribeToken: token,
      },
    });

    // Confirmation e-mail is generated by `lib/mailer`'s SMTP path when
    // configured; the preview log makes the token discoverable in dev.
    console.info(
      `[newsletter] confirmation link: ${
        process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3005'
      }/api/newsletter/unsubscribe?token=${token}`,
    );

    return res.status(201).json({
      success: true,
      message: 'Almost done — please confirm your subscription via the e-mail we just sent you.',
    });
  },
  { rateLimit: { limit: 5, windowMs: 10 * 60 * 1000 } },
);